# Docker Compose configuration for Case Interview Practice Platform development environment
# Version: 3.8 as specified in requirements
version: '3.8'

# Services configuration addressing Development Environment requirement
services:
  # PostgreSQL with Supabase extensions
  # Requirement: Database Setup - Configure local PostgreSQL database for development
  postgres:
    image: supabase/postgres:14.1.0  # Supabase-enhanced PostgreSQL image
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-case_interview_platform}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - development
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis caching service
  # Requirement: Caching System - Set up Redis caching service for local development
  redis:
    image: redis:6-alpine  # Lightweight Redis image
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_MAXMEMORY=${REDIS_MAX_MEMORY:-2gb}
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - development
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Mailhog for email testing
  # Development requirement: Email testing service configuration
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "${MAILHOG_SMTP_PORT:-1025}:1025"  # SMTP server port
      - "${MAILHOG_UI_PORT:-8025}:8025"    # Web UI port
    networks:
      - development
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1025"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

# Persistent volume configuration
volumes:
  # PostgreSQL data volume
  postgres_data:
    driver: local

  # Redis data volume
  redis_data:
    driver: local

# Network configuration
networks:
  # Development network for service isolation
  development:
    driver: bridge