# Prometheus Configuration v2.45.0
# Purpose: Primary configuration for monitoring the Case Interview Practice Platform

# HUMAN TASKS:
# 1. Verify network access to all monitoring targets (edge functions, Supabase, Redis)
# 2. Ensure firewall rules allow Prometheus to scrape metrics from all targets
# 3. Verify alertmanager service is running and accessible at alertmanager:9093
# 4. Configure authentication credentials if required by any monitoring targets
# 5. Validate storage path permissions for TSDB data retention

# Global settings applied to all scrape configurations
global:
  # Requirement: Monitoring & Observability - Configure comprehensive metrics collection
  scrape_interval: 15s     # How frequently to scrape targets
  evaluation_interval: 15s # How frequently to evaluate rules
  scrape_timeout: 10s     # Timeout for scrape requests

# Rule files containing recording and alerting rules
# Requirement: Monitoring & Observability - Configure recording rules and alert definitions
rule_files:
  - './rules/recording.yml'  # Pre-computed metrics for performance and availability
  - './rules/alerts.yml'     # Alert definitions for SLO violations

# Scrape configurations containing endpoints to monitor
scrape_configs:
  # Edge Functions Monitoring
  # Requirement: System Performance - Monitor API response times
  - job_name: 'edge-functions'
    metrics_path: '/metrics'
    scheme: 'https'
    static_configs:
      - targets: ['api.caseprep.vercel.app']
    relabel_configs:
      - source_labels: ['__address__']
        target_label: 'instance'

  # Supabase Database Monitoring
  # Requirement: Platform Stability - Track platform uptime
  - job_name: 'supabase'
    metrics_path: '/metrics'
    scheme: 'https'
    static_configs:
      - targets: ['db.caseprep.supabase.co:9090']

  # Redis Cache Monitoring
  # Requirement: System Performance - Monitor cache performance
  - job_name: 'redis'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['redis:9121']

# Alerting configuration
alerting:
  alert_relabel_configs:
    - source_labels: ['severity']
      target_label: 'alert_severity'
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Storage configuration for metrics retention
storage:
  tsdb:
    # Retain 15 days of metrics data with 50GB size limit
    retention_time: '15d'
    retention_size: '50GB'