# Prometheus Configuration v2.45.0
# Human Tasks:
# 1. Verify network connectivity to all target endpoints
# 2. Ensure firewall rules allow access to metrics endpoints
# 3. Validate SSL certificates for HTTPS targets
# 4. Configure authentication credentials if required by targets
# 5. Verify storage volume has sufficient capacity for retention period

# Global configuration
# Requirement: Monitoring & Observability - Configure comprehensive metrics collection
global:
  scrape_interval: 15s     # Default interval for metrics collection
  evaluation_interval: 15s # Default interval for rule evaluation
  scrape_timeout: 10s     # Timeout for individual scrape operations

# Rule files containing recording and alerting rules
# Requirement: System Performance - Monitor API response times
# Requirement: Platform Stability - Track platform uptime
rule_files:
  - './rules/recording.yml'  # Pre-computed metrics for performance and stability
  - './rules/alerts.yml'     # Alert definitions for SLO violations

# Scrape configurations for all monitoring targets
scrape_configs:
  # Edge Functions Monitoring
  - job_name: 'edge-functions'
    metrics_path: '/metrics'
    scheme: 'https'
    static_configs:
      - targets: ['api.caseprep.vercel.app']
    relabel_configs:
      - source_labels: ['__address__']
        target_label: 'instance'

  # Supabase Database Monitoring
  - job_name: 'supabase'
    metrics_path: '/metrics'
    scheme: 'https'
    static_configs:
      - targets: ['db.caseprep.supabase.co:9090']

  # Redis Cache Monitoring
  - job_name: 'redis'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['redis:9121']

  # Docker Container Metrics
  - job_name: 'docker-containers'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9090']

# Alerting configuration
# Requirement: Monitoring & Observability - Configure comprehensive alerting
alerting:
  alert_relabel_configs:
    - source_labels: ['severity']
      target_label: 'alert_severity'
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Storage configuration for metrics data
storage:
  tsdb:
    retention_time: '15d'    # Time-based retention
    retention_size: '50GB'   # Size-based retention